name: publish docker image

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  push_to_registry:
    name: push image to docker hub
    runs-on: ubuntu-22.04
    steps:
    - name: checkout repo
      uses: actions/checkout@v3

    - name: login to docker hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Get version
      run: echo VERSION=$(cat ./VERSION) >> $GITHUB_ENV

    - name: Check if tag exists in master
      run: |
        if git rev-parse ${{ env.VERSION }} > /dev/null 2>&1
        then
          echo "Version ${{ env.VERSION}} already exists"
          echo "TAG_EXISTS=1" >> $GITHUB_ENV
        else
          echo "Version ${{ env.VERSION}} does not exist"
          echo "TAG_EXISTS=0" >> $GITHUB_ENV
        fi

    - name: extract metadata for docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: hashibuto/countdown
        tags: |
          type=semver,pattern={{ env.VERSION }}
          type=sha

    - name: build and push docker image
      if: ${{ (github.ref == 'refs/heads/master') && (env.TAG_EXISTS == 0) }}
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Generate release
      if: ${{ (github.ref == 'refs/heads/master') && (env.TAG_EXISTS == 0) }}
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.VERSION }}
        generate_release_notes: false